---
driver:
  name: vagrant

provisioner:
  name: chef_zero 
  retry_on_exit_code:
    - 35
    - 20
    - 1
  wait_for_retry: 120
  client_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec

platforms:
  - name: debian-9.3

suites:
  - name: cinnamon
    run_list:
      - recipe[codenamephp_gui::cinnamon]
    verifier:
      inspec_tests:
        - test/smoke/cinnamon
    attributes:
  - name: xfce
    run_list:
      - recipe[codenamephp_gui::xfce]
    verifier:
      inspec_tests:
        - test/smoke/xfce
    attributes: