---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.1

suites:
  - name: cinnamon
    run_list:
      - recipe[chef.cookbook.gui::cinnamon]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
