---
driver:
  name: vagrant

provisioner:
   name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.3

suites:
  - name: cinnamon
    run_list:
      - recipe[codenamephp_gui::cinnamon]
    verifier:
      inspec_tests:
        - test/smoke/cinnamon
    attributes:
  - name: xfce
    run_list:
      - recipe[codenamephp_gui::xfce]
    verifier:
      inspec_tests:
        - test/smoke/xfce
    attributes: