AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'bundler/**'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 205

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'